name: CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install CMake
      uses: einaregilsson/setup-cmake@v1

    - name: Configure project
      run: cmake -B build

    - name: Build project
      run: cmake --build build

    - name: Run tests
      run: ctest -C Debug --output-on-failure
